### ISSUE TITLE
Dylizanse - wyswietlanie

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#10]
Wyswietlanie informacji o dylizansie stojacym na lokacji z przystankiem:
Dobrze by bylo zeby bylo oddzielne dla kazdej domeny bo wyglad dylizansow sie powtarza i np ten wyzima novi pokazuje jako nuln

#TRIGGER {^{|> }Ciemny stojacy dylizans} {#sh %ansi( 121) Nuln Wstega %ansi( 3) 3m Postoj 20s %ansi( 34)} 
#TRIGGER {^{|> }Czarny stojacy dylizans} {#sh %ansi( 121) Nuln KZ %ansi( 3) 1m 45s Postoj 20s %ansi( 34)} 
#TRIGGER {^{|> }Stary stojacy dylizans} {#sh %ansi( 121) Toskania Urbimo %ansi( 3) 2m Postoj 20s %ansi( 34)} 
#TRIGGER {^{|> }Szary stojacy dylizans} {#sh %ansi( 121) Campogrotta Varieno %ansi( 3) 1m 30s Postoj 20s %ansi( 34)} 
#TRIGGER {^{|> }Zielony stojacy dylizans} {#sh %ansi( 121) Nuln Salignac %ansi( 3) 2m 35s Postoj 20s %ansi( 34)}

**Comment by Cerdinski** [comment]
done
