### ISSUE TITLE
Dodatkowe okienko - DPS

### ISSUE THREAD

**Issue by Nurgiel** [Cerdinski/ArkadiaC#101]
W dodatkowym okienku (którego jeszcze nie ma) mogłaby być zakładka DPS z informacjami o ostatniej potyczce:

trafione + def
ilość ciosów
ilość wydefowanych
i to samo dla przeciwnika

+ jeśli się da, wyliczanie efektywnej siły ciosu, np. na zasadzie:
ledwo muskasz = 1, lekko ranisz = 2
Swietna - 7, dobra - 6
Lekko ranisz (2) zadane komus w swietnej (7) zadalo efektywnie 14 hp

Moduły w dodatkowym okienku powinno dać się włączyć/wyłączyć w Opcjach.

**Comment by Cerdinski** [comment]
Zduplikowany issue, zamykam ten a zostawiam nowszy, bo jest bardziej czytelny
