### ISSUE TITLE
Pozycja okienka Focusu

### ISSUE THREAD

**Issue by Nurgiel** [Cerdinski/ArkadiaC#103]
Okienko focusu zasłania przedostatnią linię wysyłaną przez MUDa, powinno być trochę wyżej, najlepiej dynamicznie dostosowywać się do okienka z kondycją lub jako overlay na mapie jeśli to możliwe.

**Comment by Cerdinski** [comment]
Okienko zawsze bedzie cos zaslaniac, nie da sie go umiescic na mapie.
