### ISSUE TITLE
Dobicia - npce roan + inne brakujace

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#106]
Przeswitujaca harda zjawa kobiety znika w naglym rozblysku szmaragdowego swiatla.

Szmaragdowy poblask otacza ezoteryczna zimnooka zjawe kobiety. Po chwili widmo znika, jak gdyby nigdy nie istnialo...

Przerazliwy, pelen rozpaczy krzyk nagle rozbrzmiewa w twym umysle. Ostatnie jego tony wygasaja, zanikajac wraz ze przezroczysta ponura zjawa kobiety.

Ksztalty przeswitujacej mocnej zjawy kobiety zarysowuja sie z niezwykla ostroscia, uwydatniajac rysy jej przypominajacej ludzka twarzy. Po ulamku sekundy wszystko znika, strawione przez szmaragdowy blask...

Widmowe przedmioty bedace w posiadaniu przeswitujacej hardej zjawy kobiety opadaja lekko i bezglosnie na ziemie u twych stop, po czym rozjarzywszy sie na chwile szmaragdowa poswiata nabieraja realnego wygladu i ksztaltow.

Nagle gargantuiczny upiorny ozywieniec zaczyna gwaltownie sie trzasc. Zanim dociera do ciebie, co sie dzieje, jego cialo z glosnym plasnieciem rozpada sie na tysiace kawalkow!

**Comment by Cerdinski** [comment]
done
