### ISSUE TITLE
wip - pomysly na dzialanie buttonow

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#107]
Na buttonie nr 2 zawsze prowadzacy druzyne - jesli sie nic nie dzieje i ktos inny nie jest ranny.

**Comment by Inarrit** [comment]
Moze to zabrzmi dziwnie ale... wolniejsze odswiezanie buttonow - czesto mi zdarza proba zaslaniania kogos rannego a okazuje sie, ze ktos inny juz wskoczyl na jego miejsce na buttonie.

**Comment by Cerdinski** [comment]
done
