### ISSUE TITLE
Opcje - kolorowanie ciosow zadawanych magikami

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#109]
Mozliwosc wlaczenia i wylaczenia kolorowania walki magikami

**Comment by Cerdinski** [comment]
Hej. Samo kolorowanie magikow jest wg. nastepujacych opisow. Ktore maja byc w tej opcji wylaczone ? 
mosiezna duza broszka w ksztalcie liscia debu
niewielki krwawnikowy pierscien
adamantytowa szpiczasta partyzana
adamantytowa szpiczasta partyzane
adamantytowe szpiczaste partyzany
adamantytowej szpiczastej partyzany
antyczne zdobione sztylety
antycznego zdobionego sztyletu
antyczny zdobiony sztylet
antycznym zdobionym sztyletem
azurowe koscistobiale amulety
azurowy koscistobialy amulet
bialoblekitna smocza zbroja
bialoblekitna smocza zbroje
bialoblekitne smocze zbroje
blekitno-srebrna herbowa tarcza
blekitno-srebrna herbowa tarcze
blekitno-srebrne herbowe tarcze
blekitno-srebrnej herbowej tarczy
ciemna owalna maska
ciemne owalne maski
ciezki krwisty amulet
ciezkie krwiste amulety
czarne zdobione amulety
czarnoblekitne pulsujace morgensterny
czarnoblekitnego pulsujacego morgensterna
czarnoblekitny pulsujacy morgenstern
czarnoblekitnym pulsujacym morgensternem
czarny blyszczacy kolczyk
czarny zdobiony amulet
dlugi runiczny korbacz
dlugie runiczne korbacze
dlugiego runicznego korbacza
dlugim runicznym korbaczem
dwureczne adamantytowe mloty bojowe
dwurecznego adamantytowego mlota bojowego
dwureczny adamantytowy mlot bojowy
dwurecznym adamantytowym mlotem bojowym
gigantyczne granitowe mloty
gigantycznego granitowego mlota
gigantyczny granitowy mlot
gigantycznym granitowy mlotem
gorejace dlugie talwary
gorejacego dlugiego talwara
gorejacy dlugi talwar
gorejacy dlugi talwar
gorejacy dlugi talwar
gorejacym dlugim talwarem
gruba czarna opaska
gruba czarna opaske z kolcami
grube czarne opaski
grube zlociste pierscienie z hiacyntem
grubego zlocistego pierscienia z hiacyntem
gruby zlocisty pierscien z hiacyntem
grubym zlocistym pierscieniem z hiacyntem
iskrzaca zdobiona bulawa
iskrzaca zdobiona bulawe
iskrzace zdobione bulawy
iskrzacej zdobionej bulawy
jasniejace zdobione jatagany
jasniejacego zdobionego jatagana
jasniejacy zdobiony jatagan
jasniejacym zdobionym jataganem
kosciane kilofy
koscianego kilofa
kosciany kilof
koscianym kilofem
kruczoczarne misterne miecze
kruczoczarnego misternego miecza
kruczoczarny misterny miecz
kruczoczarnym misternym mieczem
krysztalowe dwureczne korbacze
krysztalowego dwurecznego korbacza
krysztalowy dwureczny korbacz
krysztalowym dwurecznym korbaczem
kunsztowne mithrylowe topory bojowe
kunsztownego mithrylowego topora bojowego
kunsztowny mithrylowy topor bojowy
kunsztownym mithrylowym toporem bojowym
lekka lsniaca bransoleta
lekka lsniaca bransolete
lekka lsniaca para bransolet
lekkie lsniace pary bransolet
lodowe lsniace sztylety
lodowego lsniacego sztyletu
lodowy lsniacy sztylet
lodowym lsniacym sztyletem
lsniaca plomienista tarcza
lsniaca plomienista tarcze
lsniace krysztalowe wisiory
lsniace plomieniste tarcze
lsniacej plomienistej tarczy
lsniacy krysztalowy wisior
masywne amulety z czarnym opalem
masywne oksydowane pasy
masywne wyszczerbione tasaki
masywnego wyszczerbionego tasaka
masywny amulet z czarnym opalem
masywny oksydowany pas
masywny wyszczerbiony tasak
masywnym wyszczerbionym tasakiem
masywnym wyszczerbionym tasaku
misterne obosieczne topory
misternego obosiecznego topora
misterny obosieczny topor
misternym obosiecznym toporem
mithrylowa mahakamska kolczuga
mithrylowa mahakamska kolczuge
mithrylowe lsniace amulety
mithrylowej mahakamskiej kolczudze
mithrylowy lsniacy amulet
niebieskawa zdobiona bulawa
niebieskawa zdobiona bulawe
niebieskawe zdobione bulawy
niebieskawej zdobionej bulawy
niepozorne barwne pierscienie
niepozorny barwny pierscien
niewielka dziesiecioramienna gwiazda z mosiadzu
niewielka dziesiecioramienna gwiazde z mosiadzu
niewielka dziesiecioramienna gwiazdy z mosiadzu
niewielki zmatowialy pierscien
niewielkie dziesiecioramienne gwiazdy z mosiadzu
niewielkie zmatowiale pierscienie
ogromne ogniste trojzeby
ogromnego ognistego trojzebu
ogromny ognisty trojzab
ogromnym ognistym trojzebem
opalizujace runiczne topory obosieczne
opalizujacego runicznego topora obosiecznego
opalizujacy runiczny topor obosieczny
opalizujacym runicznym toporem obosiecznym
ornamentowane kruczoczarne helmy wielke
ornamentowany kruczoczarny helm wielki
plytach jego starozytnego pancerza
plytach jej starozytnego pancerza
plytach twojego starozytnego pancerza
polprzezroczysta migotliwa maczuga
polprzezroczysta migotliwa maczuge
polprzezroczysta migotliwa wlocznia
polprzezroczysta migotliwa wlocznie
polprzezroczyste migotliwe dragi
polprzezroczystego migotliwego draga
polprzezroczystego migotliwego miecza
polprzezroczystego migotliwego mlota
polprzezroczystego migotliwego sztyletu
polprzezroczystego migotliwego topora
polprzezroczystej migotliwej maczugi
polprzezroczystej migotliwej wloczni
polprzezroczysty migotliwy drag
polprzezroczysty migotliwy miecz
polprzezroczysty migotliwy mlot
polprzezroczysty migotliwy sztylet
polprzezroczysty migotliwy topor
polprzezroczystym migotliwym dragiem
polprzezroczystym migotliwym dragu
polprzezroczystym migotliwym mieczem
polprzezroczystym migotliwym mlotem
polprzezroczystym migotliwym sztyletem
polprzezroczystym migotliwym toporem
polyskliwe smukle espadony
polyskliwego smuklego espadona
polyskliwy smukly espadon
polyskliwym smuklym espadonem
poszczerbione obureczne miecze
poszczerbionego oburecznego miecza
poszczerbiony obureczny miecz
poszczerbionym oburecznym mieczem
pozlacane okulary z niebieskawych szkielek
skrzydlata pare nareczakow
smukle demoniczne miecze
smukle zmiennoksztaltne miecze
smuklego demonicznego miecza
smuklego zmiennoksztaltnego miecza
smukly demoniczny miecz
smukly zmiennoksztaltny miecz
smuklym demonicznym mieczem
smuklym zmiennoksztaltnym mieczem
snieznobiala luskowa kolczuga
snieznobiala luskowa kolczuge
snieznobiale lsniace pancerze
snieznobiale lsniace sztylety
snieznobiale luskowe kolczugi
snieznobialego lsniacego pancerza
snieznobialego lsniacego sztyletu
snieznobialej luskowej kolczugi
snieznobialy lsniacy pancerz
snieznobialy lsniacy sztylet
snieznobialym lsniacym pancerzem
snieznobialym lsniacym sztyletem
srebrzysta kosa bojowa
srebrzysta kose bojowa
srebrzyste kosy bojowe
srebrzystej kosy bojowej
starozytna runiczna zbroja plytowa
starozytna runiczna zbroje plytowa
starozytna zbroja plytowa pokryta runami
starozytne runiczne zbroje plytowe
starozytne zbroje plytowe pokryte runami
starozytnej runicznej zbroi plytowej
strzeliste zlociste helmy
strzelisty zlocisty helm
strzelistym zlocistym helmem
szara wygodna para butow
szara wygodna pare butow
szarej wygodnej pary butow
szkarlatna rogata tarcza
szkarlatna rogata tarcze
szkarlatne dlugie talwary
szkarlatne rogate tarcze
szkarlatnego dlugiego talwara
szkarlatnej rogatej tarczy
szkarlatny ciernisty pierscien
szkarlatny dlugi talwar
szkarlatnym dlugim talwarem
szmaragdowozielone misterne plaszcze
szmaragdowozielone misterne plaszcze
szmaragdowozielonego misternego plaszcza
szmaragdowozielony misterny plaszcz
szmaragdowozielony misterny plaszcz
szmaragdowozielonym misternym plaszczem
upiorne ciemne mloty bojowe
upiornego ciemnego mlota bojowego
upiorny ciemny mlot bojowy
upiornym ciemnym mlotem bojowym
waski kunsztowny sihill
waskie kunsztowne sihille
waskiego kunsztownego sihilla
waskim kunsztownym sihillem
zdobione dlugie lewaki
zdobione jasniejace mloty bojowe
zdobionego dlugiego lewaka
zdobionego jasniejacego mlota bojowego
zdobiony dlugi lewak
zdobiony jasniejacy mlot bojowy
zdobionym dlugim lewakiem
zdobionym jasniejacym mlotem bojowym
