### ISSUE TITLE
Blysk "na wroga" - pomysly

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#113]
Blysk calego ekranu na czerwono gdy sie wlazi na wroga jest mega ale... Blyska raz na zalogowanie tak wiec:

- blyskanie resetowane z aliasia + samoczynne powiedzy po tym gdy przez 15 minut nie widzialo sie danego wroga. Z palca mozna zapomniec czasem kliknac ale fajnie miec nad tym kontrole, z kolei samoczynne da pewnosci, ze w razie czego blysnie na pewno.

**Comment by Cerdinski** [comment]
done
