### ISSUE TITLE
Blad suba? Blad kk?

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#114]
Takie dziwne cos mi sie pojawialo podczas walki po wpisaniu ktok

Pokazywalo mi imie Amrasa w linii ponizej. W druzynie sama.
https://pasteboard.co/HCBmc9o.png

**Comment by Cerdinski** [comment]
Bug z kolorowaniem przechodzacym z linii na linie. Nie mam pojecia jeszcze jak to naprawic i czy wogole sie da.

**Comment by Cerdinski** [comment]
Bug cmuda, nadal brak obejscia. Zamyskam
