### ISSUE TITLE
disconnect - sub i kolorowanie

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#115]
Wysrodkowane rowno z wyswietlaniem kondycji. Linia kolorowana plynnie w kolorze suba

traci kontakt z rzeczywistoscia.
----------------------------------------- Imie ZERWALO !!!
traci kontakt z rzeczywistoscia ale nie opuszcza swiata Arkadii.
----------------------------------------- Imie ZERWALO CZESCIOWO !!!

odzyskuje kontakt z rzeczywistoscia.
----------------------------------------- Imie POLACZONO Z MUDEM

kolor #9B3F5B

**Comment by Cerdinski** [comment]
done
