### ISSUE TITLE
#walkazchoinka

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#116]
https://pasteboard.co/HCE44Qu.png - kolorowanie wkladania zbedne

**Comment by Inarrit** [comment]
Zasmarkany zezowaty goblin koncentruje sie na walce z toba.
-] zaslaniam + puszczam ->
Brudny masywny ork wspiera zoltookiego zielonego orka w walce z
wspiera cie w walce z zoltookim zielonym orkiem.
Widzisz jak szkielko porecznego kompasu peka, a cale urzadzenie po prostu rozpada ci sie w rekach.

**Comment by Cerdinski** [comment]
done
