### ISSUE TITLE
Aliasy do mapperka

### ISSUE THREAD

**Issue by ghost** [Cerdinski/ArkadiaC#122]
Aliasy ktore w roomscripcie przestawialy by wysylanie komend z numeryka **OD** danej lokacji np:
lokacje ABCDEF
A-B-C-D-E-F
stojac w lokacji c klepie jakis alias dopisuja sie odpowiednie komendy do roomsciptu danej lokacji  i teraz
klepiac z numeryka "e" zamiast "wschod" wysylana jest komenda "sprawdz kierunek;wschod" ktore dzialaja az do momentu ich wylaczenia (rowniez alias dopisujacy odpowiednia komemende w roomscripcie) np na lokacji "F"

Czyli generalnie komendy wysylane przed ruchem lub po ruchu zmieniane automatycznie w momencie wejscia na dana lokacje. 
Uzycie np: na pierwszej lokacji pustyni, w lasach, na bagnach etc

**Comment by Cerdinski** [comment]
done
