### ISSUE TITLE
Zczytywanie listy wrogow z notki i aktualizacja bazy.

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#126]
Jak w temacie - po przeczytaniu notki z lista wrogow automatycznie aktualizuje i dodaje nowe osoby do bazy

**Comment by ghost** [comment]
a co jesli notka jest nieaktualna albo postac w niej wymieniona juz nie istnieje?

**Comment by ghost** [comment]
moze by jednak pytal czy zaktualizowac wyswietlal wpisy ktore juz ma nie wiem ale tak wrzucanie z automatu to chyba nie jest najlepszy pomysl

**Comment by Cerdinski** [comment]
Format takiej notki poprosze ;) I mam podejrzenia, ze to pod konkretna gildie jest a nie ogolne skrypty.

**Comment by Cerdinski** [comment]
Jakies nowe info ?

**Comment by Inarrit** [comment]
Podrzuce format notki

**Comment by Cerdinski** [comment]
done
