### ISSUE TITLE
Kosmetyka ciosow

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#13]
**Twoje ciosy:**
<----TY 3/7 KOGO - CZYM  - cyfry na jasny niebieski
<----SS 7/8 KOGO (SS - SPEC STRAZNIKA SB SPEC BARBARZYNCY itp itd)
**W ciebie:**
TY----> 1/6 KTO - CZYM - cyfry na czerwono
<----SS 7/8 KTO - CZYM (SS - SPEC STRAZNIKA SB SPEC BARBARZYNCY itp itd)

Przelaczana opcja gagowania opisow ciosow druzyny
**Ciosy druzyny:**
<-----D 3/6 KTO - KOGO (BRAK BRONI - info o broni tylko jak ktos wali lapka)
<----SS 7/8 KTO - KOGO (SS - SPEC STRAZNIKA SB SPEC BARBARZYNCY itp itd)
**W druzyne:**
D-----> 3/6 KTO - KOGO 
SS----> 7/8 KTO - KOGO (SS - SPEC STRAZNIKA SB SPEC BARBARZYNCY itp itd)

**Wspolne:**
BRZDEK                  KOGO - NA CZYM
UNIK                      KOGO (lub puste jesli twoj)
PAROWANIE          KOGO (lub puste jesli twoj)
TARCZA               - KOGO - NA CZYM
Jesli dotyczy parowania/uniku/brzdeku/tarczy wlasnych - na jasno zielono, jesli czyjegos ciemno zielony
Pudla wygagowane

**Comment by Cerdinski** [comment]
Niestotne z powodu nowego systemu subowania ciosow.
