### ISSUE TITLE
Baza postaci BUG z apostrofem

### ISSUE THREAD

**Issue by ghost** [Cerdinski/ArkadiaC#130]
Imie:   Riann
   Opis:   ciemnowlosa zielonooka kobieta
                                      -= PC =-
 <send ':ArkadiaC:#exec -tytuly Riann' 'Pokaz historie tytulow (lacznie 2). Prawy klik by zobaczyc najnowsze.|29.07.2018 18:05:17     Noor, Mlody Osiedleniec, Wrog Scoia'tael|17.08.2018 20:37:03     Noor, Mlody Osiedleniec, Zwyciezczyni Poslancow Smierci'><color #2244CC>H</color></send> <send ':ArkadiaC:#call @isw_zmien_tytul(1024, Noor, Mlody Osiedleniec, Zwyciezczyni Poslancow Smierci)' 'Zmien tytul przypisany do tego imienia.'>Tytul</send>:   Noor, Mlody Osiedleniec, Zwyciezczyni Poslancow Smierci

   Gildia: OS - Osadnicy spod Puszczy Shekhal
   Zawod:   ? - Nieznany

**Comment by Cerdinski** [comment]
done
