### ISSUE TITLE
Subowanie ziolek - braki

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#132]
--> dwadziescia zoltych jasnych kwiatow 
-> trzy zoltoszare niepozorne ususzone korzenie 
-> jedenascie zlocistopomaranczowych duzych kwiatow

Bierzesz cztery fioletowe lejkowate kwiaty, dziesiec czterokanciastych rozgalezionych lodyg, dwa biale rozgalezione korzenie, trzy zoltoszare niepozorne ususzone korzenie i 21 zlocistopomaranczowych duzych kwiatow z otwartego pojemnego woreczka z kozlej skory.
Wez co?
Bierzesz 4 KOLA, 1 KOMOSA, 5 NOSTRZYK, 4 PRZELOT(susz), dwadziescia zoltych jasnych kwiatow, 15 LULECZNICA z otwartego pojemnego woreczka z kozlej skory.

**Comment by Cerdinski** [comment]
poprawione
