### ISSUE TITLE
Podazanie na rzece Druchii - kropka sie nie przemieszcza.

### ISSUE THREAD

**Issue by ghost** [Cerdinski/ArkadiaC#133]

**Comment by Cerdinski** [comment]
Jakies przyklady opisow ? Albo pomysly, jak ma to dzialac?

**Comment by ghost** [comment]
20:55:41 | podplyn do pnia
20:55:41 | Nie dobywasz zdobionego srebrzystego obuszka.
20:55:41 | Wchodzisz do wody.
20:55:41 | Na rzece pod skalistym brzegiem.
20:55:41 | G|Wyjscia|==> N W E
20:55:41 |          N        
20:55:41 |          |        
20:55:41 |      W---X---E    
20:55:41 |                   
20:55:41 |                   
20:55:41 | Siedem nadgnilych czerniejacych pni, trzy gnijace nabrzmiale zwloki i dwa rozgalezione zlamane konary.
20:55:41 | Cicho podplywasz do nadgnilego pnia i lapiesz sie go. Jest zimny i sliski, ale ulatwi utrzymanie sie na wodzie, zarazem kryjac przed wzrokiem obserwatorow.
20:55:46 | Utrzymujesz sie na powierzchni wody.
20:55:48 | popchnij pien na n
20:55:48 | Skryty za nadgnilym czerniejacym pniem zaczynasz plynac na polnoc.
20:55:59 | Przeplywasz, kryjac sie za nadgnilym czerniejacym pniem.
20:55:59 | Na powierzchni wartkiej rzeki.
20:55:59 | G|Wyjscia|==> N W E S
20:55:59 |          N        
20:55:59 |          |        
20:55:59 |      W---X---E    
20:55:59 |          |        
20:55:59 |          S        
20:55:59 | Dwa nadgnile czerniejace pnie.
20:56:01 | popchnij pien na n
20:56:01 | Skryty za nadgnilym czerniejacym pniem zaczynasz plynac na polnoc.
20:56:03 | Utrzymujesz sie na powierzchni wody.
20:56:17 | Przeplywasz, kryjac sie za nadgnilym czerniejacym pniem.
20:56:17 | Blisko srodka nurtu groznej rzeki.
20:56:17 | G|Wyjscia|==> N W E S
20:56:17 |          N        
20:56:17 |          |        
20:56:17 |      W---X---E    
20:56:17 |          |        
20:56:17 |          S        
20:56:17 | Nadgnily czerniejacy pien.
20:56:21 | popchnij pien na n
20:56:21 | Skryty za nadgnilym czerniejacym pniem zaczynasz plynac na polnoc.
20:56:22 | Utrzymujesz sie na powierzchni wody.
20:56:37 | Przeplywasz, kryjac sie za nadgnilym czerniejacym pniem.
20:56:37 | Wsrod wirow spienionej rzeki.
20:56:37 | G|Wyjscia|==> N W E S
20:56:37 |          N        
20:56:37 |          |        
20:56:37 |      W---X---E    
20:56:37 |          |        
20:56:37 |          S        
20:56:37 | Nadgnily czerniejacy pien.
20:56:42 | popchnij pien na n
20:56:42 | Skryty za nadgnilym czerniejacym pniem zaczynasz plynac na polnoc.
20:56:42 | Tylko niezwyklym wysilkiem udaje ci sie utrzymac na powierzchni wody.
20:56:42 | SILY [8|9]
20:56:54 | SILY [9|9]
20:56:56 | Przeplywasz, kryjac sie za nadgnilym czerniejacym pniem.
20:56:56 | Blisko srodka nurtu groznej rzeki.
20:56:56 | G|Wyjscia|==> N W E S
20:56:56 |          N        
20:56:56 |          |        
20:56:56 |      W---X---E    
20:56:56 |          |        
20:56:56 |          S        
20:56:56 | Nadgnily czerniejacy pien.
20:56:56 | SILY [8|9]
20:57:01 | Utrzymujesz sie na powierzchni wody.
20:57:08 | Przez czyste, blekitne niebo jedynie od czasu do czasu przeplywa samotna, pierzasta chmurka.
20:57:09 | popchnij pien na n
20:57:09 | Skryty za nadgnilym czerniejacym pniem zaczynasz plynac na polnoc.
20:57:21 | Utrzymujesz sie na powierzchni wody.

**Comment by ghost** [comment]
mysle ze trigger na "Skryty za ?????? ??????? pniem/konarem/zwlokami zaczynasz plynac na kierunek." 
z komenda #move styknie

**Comment by Cerdinski** [comment]
done
