### ISSUE TITLE
Zabezpieczenie rzeczy liczy jak odlozenie

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#136]
NIETYPOWA POLKSIEZYCOWATA HALABARDA (bron drzewcowa) wywazenie(9|14) skutecznosc(12|14) (7600g|1300ml) (MAX|7) [21|28] Odloz Zabezpiecz 
NIETYPOWA POLKSIEZYCOWATA HALABARDA (bron drzewcowa) wywazenie(8|14) skutecznosc(9|14) (7600g|1300ml) (MAX|7) [17|28] Odloz Zabezpiecz 
Lacznie: 3 przedmiotow wartych 1440md (6zl)
zabezpiecz 2. nietypowa polksiezycowata halabarde
Juz zabezpieczone: nietypowa polksiezycowata halabarda.
zabezpiecz 2. nietypowa polksiezycowata halabarde
Juz zabezpieczone: nietypowa polksiezycowata halabarda.
SILY [3|9]
Ten przedmiot zostal odlozony.

Zabezpieczalam 2 i 3

**Comment by Cerdinski** [comment]
done
