### ISSUE TITLE
Otulanie sie plaszczem - bug przy zerwaniu polaczenia

### ISSUE THREAD

**Issue by Tryggvi11** [Cerdinski/ArkadiaC#139]
Jak zerwiesz polaczenie i zalogujesz sie ponownie to skrypt sadzi, ze nie jestes otulony plaszczem mimo, ze jestes.

--> Nie masz na sobie plaszcza!                           Kliknij tutaj zebym sie zamknal.
                                  BIND  `   [ OTUL SIE PLASZCZEM ]

**Juz jestes otulony plaszczem.**

--> Nie masz na sobie plaszcza!                           Kliknij tutaj zebym sie zamknal.
                                  BIND  `   [ OTUL SIE PLASZCZEM ]

--> Nie masz na sobie plaszcza!                           Kliknij tutaj zebym sie zamknal.
                                  BIND  `   [ OTUL SIE PLASZCZEM ]

**Comment by Cerdinski** [comment]
done
