### ISSUE TITLE
Wycie o plaszcz mimo otulenia

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#142]
--> Nie masz na sobie plaszcza!                           Kliknij tutaj zebym sie zamknal.
                                  BIND  `   [ OTUL SIE PLASZCZEM ]

otul sie plaszczem
Juz jestes otulona plaszczem

Jestes szczelnie otulona grubym brazowym futrem, a jego kaptur skrywa twoja twarz w cieniu.

**Comment by Cerdinski** [comment]
done
