### ISSUE TITLE
Pomysl - Dodanie strzalek podczas ucieczki wroga

### ISSUE THREAD

**Issue by Tryggvi11** [Cerdinski/ArkadiaC#143]
W obecnej chwili jest tak:

**Brudny dziecinny snotling UCIEKA na [= NW =]**

Jest mozliwosc, zeby dodac strzalki pokazujace kierunek?

**Comment by ghost** [comment]
Dodam, że mogłoby być włączane/wyłączane w opcjach :>

**Comment by Cerdinski** [comment]
done
