### ISSUE TITLE
Mnóstwo błędów w File - Compatibility Report

### ISSUE THREAD

**Issue by ghost** [Cerdinski/ArkadiaC#148]
Trigger biblioteka_ksiazki
   %i within quotes is not expanded [Help] : #sub {@pad_left(%1,4)"<send '#va biblioteka_ksiazka {%literal("%2")};#sendraw oddaj ksiazke;wypozycz ksiazke "%1"'>"%2"</send>"}

Trigger {|> }(*) zaprasza cie do swojej druzyny.$
   Command not supported : #break

Trigger przekazuje(sz)? prowadzenie druzyny
   Does not compile : error in floating point value at row 0 col 45

Trigger ^{|> }(*) jest ({@kd_kondycje})({a|e|y|}). Atakujesz ({go|ja}).$
   [] immediate evaluation syntax no longer used [Help] : [%ismember( %lower( %1), @kd_druzyna)%char( 93))%ansi( 11)"===" "["1"]

Alias -logins
   OR operator changed from | to || [Help] : )|(

Alias -postepy
   OR operator changed from | to || [Help] : )|(
   String list should be enclosed in {} instead of "" : = "select rowid, postac, date(start,'localtime') as data, time(start,'localtime') as start, time(stop,'localtime') as stopp, ltrim(time(strftime('%s',stop)-strftime('%s',start),'unixepoch'),'0:') as czas, postepy, round(CASE WHEN finished=0 THEN 100.0*czas_walki/CASE WHEN postepy='kosmiczne' THEN sredni_postep ELSE max(sredni_postep,czas_walki) END END) as part, round(CASE WHEN forma>0 THEN CASE WHEN finished=1 THEN 100.0*(forma)/czas_walki ELSE 100.0*forma/CASE WHEN postepy='kosmiczne' THEN sredni_postep ELSE max(sredni_postep,czas_walki) END END END) as form, ltrim(time(czas_walki,'unixepoch'),'0:') as incombat, round(100.0*czas_walki/(strftime('%s',stop)-strftime('%s',start))) as comb, ltrim(time(czas_leczenia,'unixepoch'),'0:') as healing, round(100.0*czas_leczenia/(strftime('%s',stop)-strftime('%s',start))) as heal, (select co_zabito||' '||postep_ile_zabito || '/' || postep_ile_zabito_druzyna from postepy_zabici where postep_id=postepy.rowid order by postep_ile_zabito_druzyna desc limit 1) as max_zabici from postepy where (finished=1 or CASE WHEN finished=0 THEN 100.0*czas_walki/CASE WHEN postepy='kosmiczne' THEN sredni_postep ELSE max(sredni_postep,czas_walki) END END >=5.0) and "

Trigger ^Jestes ([a-z]+)([yia]), ([a-z]+)([yia]), ([a-z]+(?: [a-z]+)?)([
   <> immediate expansion syntax no longer used [Help] : <@lc_db.%key,12,10)) $subl = "?" #if (@st_db.headache>

Trigger ^{|> }Zrecznie zaslaniasz
   Does not compile : error in floating point value at row 2 col 26

Trigger ^{|> }Stajesz u boku *, gotowa w kazdej chwili zaslonic {ja|go}
   Does not compile : error in floating point value at row 1 col 26

Trigger ^{|> }Na rozkaz * zaslaniasz
   Does not compile : error in floating point value at row 2 col 26

Alias -zabici
   OR operator changed from | to || [Help] : )|(

Trigger ^Nie jestes w stanie dluzej czytac.$
   %i within quotes is not expanded [Help] : zs.cmd.print("--> Pelna mana przy trzezwym okolo: " .. os.date("%H:%M",os.time()+5940) .. "\r\n")

Trigger ^[a-z]++ uczy cie mowic w
   %i within quotes is not expanded [Help] : zs.cmd.print("--> Pelna mana przy trzezwym okolo: " .. os.date("%H:%M",os.time()+5940) .. "\r\n")

Trigger ^Gdzies wysoko, na nocnym niebie miga ci jakis olbrzymi cien. Zm
   Does not compile : error in floating point value at row 3 col 84

Alias -tytuly
   %i within quotes is not expanded [Help] : #print %ansi( 2)" --- Historia tytulow dla "%ansi( 7)%char(27)"[1z<send '#call @isw_pokaz(%literal("%proper( %1)"))' 'Pokaz wpis dla "%proper( %1)"'>"%char(149)"</send> "%proper( %1)%ansi( 2)" -------"

Alias -ktoto
   %i within quotes is not expanded [Help] : $imie = " (NPC) <color #2255FF><send '#call @isw_pokaz(%literal(!NPC"$q.Item("rowid")"))' 'Pokaz wpis tego NPC.'>"%char(149)"</send></color> "$imie%repeat(" ",(14-%len($imie)))

Trigger Ktos_kogos_przedstawia
   Does not compile : error in floating point value at row 0 col 45
   %i within quotes is not expanded [Help] : (state 1) $opis = %subregex(%t1,"(iego|ego)\b","%if((?MEMBER:1)=1,i,y)")

Trigger Ktos_sie_przedstawia
   Does not compile : error in floating point value at row 0 col 45

Alias -ziolo
   %1 within quotes is not expanded [Help] : local pat2 = pat:gsub("([+-])","%%%1"):gsub("(%a)", 
   %%1 not supported [Help] : %%%1

**Comment by Cerdinski** [comment]
Na każda z tych linii odpowiadałem juz z ponad miesiac temu na prv, 
nie jest moja wina ze compability raport wykrywa problemy tam gdzie ich nie ma, ani ze twierdzi, ze poprawnie udokumentowana i działająca funkcja #break nie istnieje. 

Linie z "won't compile" u mnie nie występują, prawdopodobnie jakiś błąd przy updacie/instalacji, świeża instalka powinna na to pomóc.
