### ISSUE TITLE
Button z kacem

### ISSUE THREAD

**Issue by Handalia** [Cerdinski/ArkadiaC#15]
Możnaby podzielić button upicia na upicie i na dole kac, ewentualnie w jakiś sposób przy samej trzeźwości sprawdzać kac i podmieniać trzeźwość na poziom kaca

**Comment by Cerdinski** [comment]
Fajny pomysl. Ogolnie te buttony ze statusem w planach beda zamienione na cos innego. Cmud wydaje sie z  butonnami nie lubic.

**Comment by Cerdinski** [comment]
Done
