### ISSUE TITLE
-postepy

### ISSUE THREAD

**Issue by ghost** [Cerdinski/ArkadiaC#152]
![cus](https://user-images.githubusercontent.com/21083932/47619679-eb997680-dae1-11e8-95ac-bb26734bed60.jpg)

**Comment by Cerdinski** [comment]
Błąd nie występuje ani u mnie, ani na dwóch innych komputerach do których mam bezpośredni dostęp. Jesteś pewien, że nie dopisałeś czegoś przez przypadek ? Wygłada na przypadkowo dodaną kropke w losowym miejscu kodu. Jeżeli tak, to reinstalka tej klasy powinna pomóc, jeżeli nie to bedziemy myśleć

**Comment by ghost** [comment]
nowa wersja rozwiazala problem
