### ISSUE TITLE
Suby speca GP

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#156]
Klute:
Wykorzystujac dogodny moment wyprowadzasz celne pchniecie teczowa dluga wlocznia w duzego smierdzacego snotlinga, lekko raniac go w nogi.
Wykorzystujac dogodny moment wyprowadzasz celne pchniecie teczowa dluga wlocznia w ciemnozielonego zwinnego snotlinga, raniac go w korpus.
Wykorzystujac dogodny moment wyprowadzasz celne pchniecie teczowa dluga wlocznia w krepego siakajacego snotlinga, powaznie raniac go w korpus.
Wykorzystujac dogodny moment wyprowadzasz celne pchniecie teczowa dluga wlocznia w krepego siakajacego snotlinga, bardzo ciezko raniac go w nogi.
Wykorzystujac dogodny moment wyprowadzasz celne pchniecie teczowa dluga wlocznia w ciemnozielonego zwinnego snotlinga, masakrujac go w nogi.

Wykorzystujac dogodny moment wyprowadzasz celne pchniecie teczowa dluga wlocznia w straszliwa rozwscieczona zjawe, lecz ta oslania sie w pore kolczasta stalowa tarcza.
Wykorzystujac dogodny moment probujesz wyprowadzic celne pchniecie teczowa dluga wlocznia w straszliwa rozwscieczona zjawe, lecz ta zwinnie unika ciosu.

**Comment by Inarrit** [comment]
Ciete:
Wykorzystujac dogodny moment probujesz wyprowadzic celne ciecie mysliwskim smuklym kordelasem w poteznego ryzego dzika, lecz ten zwinnie unika ciosu.
Wykorzystujac dogodny moment wyprowadzasz celne ciecie mysliwskim smuklym kordelasem w poteznego ryzego dzika, ledwo muskajac go w tulow.

**Comment by Cerdinski** [comment]
Brak opisow:
Pudlo
Brzdek o zbroje
Wyparowane bronia

**Comment by Cerdinski** [comment]
Niestotne z powodu nowego systemu subowania ciosow.
