### ISSUE TITLE
Skrypcik paczkowy

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#157]
Po podjeciu paczki dodatkowa komenda "ob paczke" zeby w rozszerzeniu pojawiła się pełna informacja do kogo jest paczka - imie i zawod.
Obecnie jest tak:
https://pasteboard.co/HNHWl84.png
Po "ob paczke" tak:
https://pasteboard.co/HNHWC4u.png

Kosmetyczna zmiana:
1. https://pasteboard.co/HNHUoEO.png
Pomiędzy : a Adresatem brak podkreslenia tekstu.

2. https://pasteboard.co/HNHUwA5.png
Przy pilnej paczce zmiana koloru podswietlenia tekstu na powiedzmy #F47142

**Comment by Cerdinski** [comment]
done
