### ISSUE TITLE
Wschody i zachody slonca - brakujace opisy

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#163]
Ostatnie slabe promienie slonca cofaja sie pograzajac caly las w mroku nocy.

Slonce z trudem przebija sie przez galezie zwiastujac nastanie nowego dnia, jednak mgla nie ustepuje nadal otulajac wszystko dookola grubym, mlecznobialym plaszczem.

**Comment by Cerdinski** [comment]
done
