### ISSUE TITLE
Schodzenie z gory - cofki

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#164]
Przy schodzeniu w dol nie powinno byc cofki na mapie na lokacje z ktorej zaczelismy zlazic. Powod raczej jasny - spadlismy  wiec lokacja sie zmienila. Nie wiem czy da rade to jakos polaczyc z komenda "zejdz na dol" bo opis jest identyczny przy odpadaniu gdy probuje sie wejsc na gore i tutaj cofka juz jak najbardziej wskazana.
WIP - brak kompletnych opisow spadania.
Zaczynasz schodzic na dol.
Odpadasz od sciany i lecisz w dol, jednak dzieki niewielkiej wysokosci udaje ci sie zgrabnie wyladowac na ziemi.

**Comment by Cerdinski** [comment]
done
