### ISSUE TITLE
Restet dostarczenia paczki 

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#165]
12:31:39 | zwroc paczke
12:31:39 | Zwracasz skrupulatnemu schludnemu mezczyznie pocztowa paczke.
12:31:39 | Skrupulatny schludny mezczyzna kreci z dezaprobata glowa.

i wersja gdy nie ma npca:
zwroc paczke
Zwracasz pracownikowi poczty paczke.
Pracownik poczty kreci glowa z dezaprobata.

**Comment by Cerdinski** [comment]
done
