### ISSUE TITLE
Bledy po wcisnieciu gwiazdki

### ISSUE THREAD

**Issue by ghost** [Cerdinski/ArkadiaC#166]
`Oboz orkow.
G|Wyjscia|==> SW NE NW
[3] Czarnooki nerwowy ork, czerwonooki bezwzgledny ork i niski zasmarkany snotling.
Czerwonooki bezwzgledny ork rozglada sie.
-] atakuje -> <color #808000>niski zasmarkany snotling, czarnooki nerwowy ork</color>
-] atakuje -> czerwonooki bezwzgledny ork
Niski zasmarkany snotling piszczy do ciebie: Taka duse a taka gupie.
                   A T A K U J E S Z ===>  niskiego zasmarkanego snotlinga
                   A T A K U J E S Z ===>  czarnookiego nerwowego orka
Slucham?
                   A T A K U J E S Z ===>  czerwonookiego bezwzglednego orka
Czarnooki nerwowy ork spluwa krotko na ziemie.
Niski zasmarkany snotling piszczy jakies dziwne slowa.`

**Comment by Cerdinski** [comment]
done
