### ISSUE TITLE
Skrypt nie koloruje postaci bedacych na "listach" w notkach pisanych przez graczy.

### ISSUE THREAD

**Issue by ghost** [Cerdinski/ArkadiaC#169]
Czasami sie przydaje, chocby wtedy jak ktos wstawia swoja liste wrogow do jakiegos posta na tablice a my chcemy sobie sprawdzic czy rzeczywiscie mamy "wszystkich". Jest to potrzebne raz na jakis czas, wiec mozna by dodac do opcji domyslnie wylaczone.

**Comment by ssnakey** [comment]
Czasami sie przydaje, chocby wtedy jak ktos wstawia swoja liste wrogow do jakiegos posta na tablice a my chcemy sobie sprawdzic czy rzeczywiscie mamy "wszystkich"

**Comment by Cerdinski** [comment]
Skrypt nie koloruje ludzi, ktorzy nie zostali spotkani w tym zalogowaniu ani zobaczeni w kto. Jest to zrobione ze wzgledow wydajnosciowych.
