### ISSUE TITLE
Opcje - wyswietlanie kondycji opisow

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#17]
Dodanie opcji by w okienku kondycji - nie na buttonie wyswietalo kondycje albo w formie:
   -• IMIE   ( @)##########      
Albo 
   -• IMIE   ( @)W SWIETNEJ KONDYCJI

**Comment by Cerdinski** [comment]
Poprawiono czytelnosc z inny sposob, tak, ze nie powinno byc to potrzebne. Jezeli z jakis powodow nadal jest, wrzuc ta issue ponownie.
