### ISSUE TITLE
Statki/dylki/wozy/pierdoly opisy

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#171]
Na pokladzie:
Statek odbija od brzegu.
Statek przybija do brzegu.
Prom odbija od brzegu.
Prom przybija do brzegu.

Zaloga szybko odcumowuje statek, ktory powoli, majestatycznie zaczyna oddalac sie od brzegu.
Drzenie przebiega poklad, gdy okret przybija do brzegu przystani. Marynarze sprawnie cumuja go i wysuwaja na brzeg trap.

Na nabrzezu:
Szeroki drewniany prom przybija do brzegu.
Rzeczny transportowy statek odbija od brzegu.
Rzeczny transportowy statek przybija do brzegu.

Przystanek:
Czarny stojacy dylizans powoli rusza w droge, zmierzajac na polnocny-zachod.
Czarny jadacy dylizans powoli zatrzymuje sie.

Z wnetrza:
1
Woznica donosnym glosem oznajmia odjazd.
Powoz powoli, jakby z wysilkiem, rusza z miejsca.

Powoz cicho skrzypiac zatrzymuje sie.

2
Woznica oznajmia odjazd.
Woznica trzaska z bata i dylizans rusza, kolyszac sie na boki.

Monotonne kolysanie ustaje w koncu i woz zatrzymuje sie.

3
Z przodu woznica znuzonym glosem oznajmia odjazd.
Trzaskaja lejce i woz rusza, ospale kolyszac sie na boki.

Brakujacy woz w Ish:

                  
Kupiecki stojacy woz z plandeka.
Tretogor - Gelibol

**Comment by Cerdinski** [comment]
na podstawie tego zrobiono licznik czasu podrozy
