### ISSUE TITLE
Wsiadanie do obiektow - poprawa aliasu

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#172]
Poprawka wymagana ze wzgledu na zlikwidowanie z jakis dziwnych powodow komendy "wejdz do obiektu"

otworz sakiewke
wez monety z przytroczonej sakiewki
kup bilet
wejdz na statek
wsiadz do dylizansu
wejdz do wozu
wejdz do powozu
wejdz na woz
wloz monety do przytroczonej sakiewki
zamknij sakiewke

**Comment by Cerdinski** [comment]
done
