### ISSUE TITLE
Brakujace wschody/zachody vol 2

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#174]
_Pierwsze promienie wschodzacego slonca rozswietlaja niebo. Rozpoczyna sie kolejny dzien.
Pierwsze promienie wschodzacego slonca rozswietlaja niebo. W Starym Swiecie rozpoczyna sie kolejny dzien._
Ta dwa zrobione

**Comment by Cerdinski** [comment]
done
