### ISSUE TITLE
Skrypt porównujący wszystkich na lokacji.

### ISSUE THREAD

**Issue by gnomidlo** [Cerdinski/ArkadiaC#175]
Pomysł na skrypt, który porówna wszystkich na lokacji z nami i wyświetli podsumowanie w formie tabelki.

Jakby były możliwe opcje/komendy do:
- porównania wszystkich;
- porównania tylko osób nie będących w drużynie;
- porównania tylko wrogów;
- wygagowanie opisów porównanie i wyświetlenie tylko tabeli podsumowującej.

**Comment by Cerdinski** [comment]
done
