### ISSUE TITLE
Mozliwosc zaskakiwania zamiast atakowania

### ISSUE THREAD

**Issue by elenril2** [Cerdinski/ArkadiaC#181]
Propozycja, zeby skrypt, ktory odpowiada za wykonanie manewru zabij, sprawdzal, czy postac gracza jest ukryta i wtedy zamiast zamiast zabij dawal komende zaskocz. Mozna to regulowac jakims buttonem.

**Comment by Cerdinski** [comment]
dodano, jako opcja
