### ISSUE TITLE
alias na szeptanie prowadzacemu aktualnego zmeczenia ewentualnie zmeczenia pragnienia i sytosci -melduj

### ISSUE THREAD

**Issue by ghost** [Cerdinski/ArkadiaC#183]

**Comment by elenril2** [comment]
Ja posiadam prosty skrypt, informujący o aktualnym zmęczeniu. Mam tez podpiętego go do akcji wykonywanej po kliknięciu na pasek zmęczenia w oknie walka.

`<alias name="-melduj">
    <value>zmeczenie
#IF (@st_db.fatigue &gt; 7) { 'Nie jestem zmeczony.} { 'Jestem @st_db.ofatigue }</value>
  </alias>`

**Comment by Cerdinski** [comment]
done
