### ISSUE TITLE
Baza postaci - spis problemow i propozycji

### ISSUE THREAD

**Issue by elenril2** [Cerdinski/ArkadiaC#184]
### Ponizej w oddzielnych postach bede dodawal znalezione problemy lub propozycje zwiazane z obsluga istot w skrypcie.

**Comment by elenril2** [comment]
**Widok istoty:**
_[problem]_ nie mozna skasowac przypisanego tytulu (mozna ew. wstawic pusta spacje) _=> wpisanie znaku "!" spowoduje skasowanie tytulu_
_[problem]_ przy probie edycji tytulu pojawia sie tylko pierwszy czlon (do pierwszego znaku ",")
_[problem]_ nie mozna wpisac znaku apostrofu ("'") w tytule (pojawia sie on w nazwiskach, przydomkach, nazwach wlasnych) _=> dodac escape'owanie znakow dozwolonych w tytulach_
_[problem]_ skrypt pozwala wpisac do okna z tytulem niedozwolony znak (jak "!" lub "/"), przypisuje go do bazy, ale przy probie zmiany wyrzuca juz blad _=>dodac liste znakow zakazanych w tytulach_

**Comment by elenril2** [comment]
**Ogolne:**
_[problem]_ baza ma bardzo wiele dubli pomiedzy postaciami i NPC (najprawdopodobniej wiekszosc przepisane z dwarfa, ale mozliwe, ze dodaja sie tez nowe - do zweryfikowania)
_[problem]_ wiele NPC w bazie to w rzeczywistosci Postaci (najprawodpodbniej wiekszosc przepisane z dwarfa, ale mozliwe, ze dodaja sie tez nowe niepoprawnie - do zweryfikowania)

**Comment by elenril2** [comment]
**Wyszukiwanie istot:**
_[propozycja]_ wyszukiwanie tylko przy ponad trzech znakach (przy dwoch nieraz jest zbyt wiele wynikow i laguje)
_[problem]_ przy wyszukiwaniu NPC po imieniu, skrypt przechodzi niepoprawnie do widoku Postaci o tym samym ID, co wyszukiwany NPC

**Comment by elenril2** [comment]
**Grupy:**
_[propozycja]_ dodanie mozliwosci zmiany nazwy grupy
_[propozycja]_ dodanie mozliwosci wpisania komentarza dla grupy

**Comment by elenril2** [comment]
**Widok grup/gildii:**
_[propozycja]_ jesli dana Grupa lub Gildia ma przypisany kolor mozna go podstawic do jej nazwy na ekranie z lista

**Comment by elenril2** [comment]
_[11] [Kerhenia], [Vailen], [Hardin], [Skavo], [Ilane], [Asael], [Lumen], [Taiven], [Senvil], [Diriana] i Ulav.
    (SC|P) • Ulav          niewysoki energiczny gnom_
klikniecie na liczbę pokazało info tylko o nieukrytym, skrypt powinien przed analizą wycinać nawiasy kwadratowe [], bo w tym raczej leży problem

**Comment by Cerdinski** [comment]
All done
