### ISSUE TITLE
Pokazywanie ogluszen / rozbrojen czlonkow druzyny

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#185]
Ciemnooki malomowny straznik szybkim niczym mysl ruchem ciezkiej dlugiej halabardy wytraca posrebrzany dlugi miecz z reki Chora.
Falik szybkim niczym mysl ruchem srebrzystej kosy bojowej wytraca ciezka karbowana maczuge z rak muskularnego paskudnego trolla.

npc:
Yannick szybkim niczym mysl ruchem smuklego bladoczerwonego miecza wytraca poszczerbiony obureczny miecz z rak Drachena.
Yannick szybkim niczym mysl ruchem smuklego bladoczerwonego miecza wytraca ci srebrzysta kose bojowa z rak. Czujesz paralizujacy bol w wykreconych ciosem dloniach.

**Comment by Inarrit** [comment]
Nie silac sie na wirtuozerie Balkrag z calej sily wali wysoka cuchnaca mumie na odlew srebrzystym kanciastym mlotem bojowym, obijajac jej przy tym obandazowana glowe. Nieprzyjemne chrzakniecie i metny wzrok przeciwnika swiadcza, ze dobrze wymierzony cios musial trafic w jakies wrazliwe miejsce.

granit: 
Nie tracac czasu na zbedne manewry Brygu z calej sily wali ognistookiego mrocznego demona na odlew gigantycznym granitowym mlotem, obijajac mu przy tym korpus. Nieprzyjemne chrzakniecie i metny wzrok przeciwnika swiadcza, ze dobrze wymierzony cios musial trafic w jakies wrazliwe miejsce.

**Comment by Inarrit** [comment]
Niespodziewanie kamienny golem wyciaga reke i uderza w glowe Diriane.

**Comment by Cerdinski** [comment]
done
