### ISSUE TITLE
Ilosc zabitych na postep

### ISSUE THREAD

**Issue by elenril2** [Cerdinski/ArkadiaC#187]
Proponuje dodac przy informacji o zrobieniu postepu dane o tym, ile zabilo sie npc na ten wlasnie poziom. Mozna rozwinac funkcjonalnosc aliasu -za. Dodac do niego dodatkowe parametry, zeby moc wyswietlic zabitych w danym postepie (takze tym aktualnym, jeszcze nieskonczonym).

**Comment by Cerdinski** [comment]
done
