### ISSUE TITLE
Błąd bindowania ` w karczmie

### ISSUE THREAD

**Issue by jorhni** [Cerdinski/ArkadiaC#19]
Znalezione w Nuln - "Pod Wielkim Dzikiem"

>08:45:52 | usiadz

>08:45:52 | Gdzie chcesz usiasc? Przy brudnym stole, przy szerokim stole czy przy dlugim barze?

>08:45:52 |                                            BIND ` ----> USIADZ PRZY BRUDNYM STOLE, PRZY SZEROKIM STOLE CZY PRZY DLUGIM BARZE

Wciskamy binda i mamy:

>08:45:54 | usiadz przy brudnym stole, przy szerokim stole czy przy dlugim barze

>08:45:54 | Gdzie chcesz usiasc? Przy brudnym stole, przy szerokim stole lub przy dlugim barze?

>08:45:54 |                                            BIND ` ----> USIADZ PRZY BRUDNYM STOLE, PRZY SZEROKIM STOLE LUB PRZY DLUGIM BARZE

**Comment by Cerdinski** [comment]
done
