### ISSUE TITLE
Tagi manewrow kondycji

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#193]
Mozliwosc srodkowania i rownania do lewej tagow w tym samym konfigu. przykadlowo - kondycje zostaja na srodku razem z tagiem ogluszenia, rozbrojenia itp ale juz np puszczanie zaslon i inne zostaje po lewej i nie smieci srodka, gdzie powinny byc informacje najwazniejsze.

**Comment by Cerdinski** [comment]
done
