### ISSUE TITLE
Problem z ikonkami przy obsłudze dzwięków

### ISSUE THREAD

**Issue by jorhni** [Cerdinski/ArkadiaC#20]
Przy nowych zdarzeniach "dźwiękowych" windows spamuje ikonami w tray`u odpowiedzialnymi za ffdshow audio decoder. Wg obserwacji ikonki nie sumują się, tylko po ponownym wystąpieniu zdarzenia, jak gdyby się resetowały i pojawiały na nowo - przykład:
wchodzimy na lokację, gdzie atakuje nas 3 przeciwników, pojawiają się 3 ikonki, po pokonaniu ich (dźwięk oznaczający zabicie przeciwnika nie wywołuje pojawienia się ikonki) wchodzimy na kolejną lokację, gdzie jest 5 przeciwników, którzy nas atakują. W tej sytuacji już widniejące 3 ikony zostają zresetowane i na ich miejsce pojawi się 5 (tyle zdarzeń dźwiękowych było związanych z atakiem na naszą postać).

**Comment by Cerdinski** [comment]
Szybkie badania wykazaly, ze jest to normalne. Cmud potrzebuje jednego zestawu kodekow odpalonego na kazdy dzwiek, ktory ma byc odgrywany jednoczesnie. Nie wyglada to na szkodliwe na dluzsza mete.
