### ISSUE TITLE
Bind usiadz

### ISSUE THREAD

**Issue by Handalia** [Cerdinski/ArkadiaC#28]
Gdzie chcesz usiasc? Przy drewnianym stole czy przy drugim drewnianym stole?
                                            BIND ` ----> USIADZ PRZY DREWNIANYM STOLE CZY PRZY DRUGIM DREWNIANYM STOLE

Trigger nie zakłada wyjątku dwóch wyborów.

**Comment by Cerdinski** [comment]
Poprawione
