### ISSUE TITLE
Wyswietlanie cech cdn

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#33]
Pod wpływem alko dzieją się cuda:

cechy
Jestes mocarna (troche), akrobatyczna (), atletyczna (?), inteligentna (?) i nieugieta (?).
https://pasteboard.co/HpyBPyB.png

**Comment by Cerdinski** [comment]
- Od teraz obnizone i podwyzszone ze wzgledu na kaca/alkochol cechy beda mialy odpowiednie wyjasnienie
  w nawiasie. ? w nawiasie bedzie pokazywane tylko w przypadku naturalnego podwyzszenia/obnizenia cechy
Dodano obslluge epika i nadludzia w nawiasach
