### ISSUE TITLE
Brak dostosowania wyswietlania linii do wielkosci okna

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#35]
Jak w temacie:

https://pasteboard.co/HpZHT8S.png

Upierdliwe bo trzeba przesuwac okno zeby zobaczyc calosc opisu, w tym wypadku zawartosci ekwipunku

**Comment by Cerdinski** [comment]
To jest blad cmuda, ktory czasami sie pojawia po wyskoczenia innego bledu z dostepem do pamieci. Nie jestem w stanie nic na to poradzic, wlaczenie/wylaczenie naprawia
