### ISSUE TITLE
Baza postaci nie koloruje wszystkich ktorych powinna, czeste crashe.

### ISSUE THREAD

**Issue by ssnakey** [Cerdinski/ArkadiaC#42]
Jak w temacie zilustrowano na filmikach:
https://we.tl/Gmw15Kz1qI
https://we.tl/sONW44Vg7t
Linki beda aktywne przez 7 dni.

**Comment by Cerdinski** [comment]
Nie kolorowanie to blad, jezeli w kolorowanej grupie po imieniu jest znana osoba z wiecej niz jedna ignorowana koncowka. Poprawie w nastepnej wersji.

**Comment by Cerdinski** [comment]
Poprawiony bug z koncowkami.

Co do stabilnosci otwierania okna to jest to znany blad, nadal nie znam na niego zadnego rozwiazania
