### ISSUE TITLE
Roznosci na mapie

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#47]
Na zmudzie robilam sobie roomscripty w lokacji ktore na tej lokacji wykonuja rozne rzeczy przynalezne do lokacji. Np:

Szybkie kupowanie ziol:
#key KEY0 {kup 10 dziurawcow;kup 10 delion;kup 10 kol;kup 10 naparstnic;kup 10 kasztanowcow;kup 5 nostrzykow;kup 10 barwinek;kup 10 lulecznic;kup 5 babek;kup 5 pieciornikow;kup 5 arnik}
#ALARM +1 {#sh %ansi( 121) NUM0 %ansi( 46) ZIOLA %ansi( 34)}

Szybkie sprawdzenie depozytu:
#key KEY0 {przejrzyj depozyt}
#ALARM +1 {#sh %ansi( 121) NUM0 %ansi( 46) SKRYTKA %ansi( 34)}

Pytanie o zlecenie, przeczytanie listu, zjadanie kapusty, sprawdzanie aukcji i wszystko inne co tam kazdy sobie wymysli. Ot wzor jak to zrobic starczy ;) Oczywiscie to powyzsze nie dziala pod cmudem.

**Comment by Cerdinski** [comment]
done
-mbind
