### ISSUE TITLE
Follow na mapie - Poczta w Averheim

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#49]
Poczta w Aver - wyjscia na n i na w oba: Podazasz za * na rynek.

**Comment by Cerdinski** [comment]
Dodane jako czesc podkomendy follow (-lbind follow), wpisz na lokacji 
-lbind f na rynek > GMCP

A po podazeniu na rynek z tej lokacji na nastepnej lokacji zostanie sprawdzona pozycja uzywajac GMCP
