### ISSUE TITLE
Błędne wyświetlanie skali ciosów

### ISSUE THREAD

**Issue by zjadaczkorzeni** [Cerdinski/ArkadiaC#55]
Ciosy zadane i otrzymane mają siłę x/6 poza 2 i 3, które mają na 7(3/7; 2/7)

![image](https://user-images.githubusercontent.com/25790577/41875221-82075c6a-78ca-11e8-8cde-74b5c6ce8794.png)

**Comment by Cerdinski** [comment]
poprawione
