### ISSUE TITLE
Brak rysowania wyjsc na wodzie

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#57]
Na powierzchni jeziora.
Mozesz skierowac lodz na polnocny-wschod, poludniowy-wschod, poludnie, wschod, poludniowy-zachod, polnoc, polnocny-zachod oraz zachod.

**Comment by Cerdinski** [comment]
Widocznie wyjscia na wodzie nie sa tagowane jako wyjscia przez GMCP ? Przyjrze sie jak to wyglada gdy bede mial mozliwosc

**Comment by Inarrit** [comment]
Blad zgloszony na arce, zobaczymy co z tego bedzie

**Comment by Cerdinski** [comment]
done
