### ISSUE TITLE
Medytacja nie rozpoznaje epika i nadludzia

### ISSUE THREAD

**Issue by Cerdinski** [Cerdinski/ArkadiaC#6]
I nie bedzie az mi ktos tutaj nie wklei jak to wyglada i jak to jest mechanicznie ;)

**Comment by Inarrit** [comment]
Jestes mocarna (?), akrobatyczna (?), muskularna (?), bystra (?) i dzielna (?).

     SUBLEVEL STR 2/4 (troche)          37
Masz epicka zrecznosc.
     SUBLEVEL WT  3/4 (niewiele)        33
     SUBLEVEL INT 3/4 (niewiele)        28
     SUBLEVEL ODW 1/4 (duzo)            26

**Comment by Cerdinski** [comment]
Ok, rozpoznaje juz epika. Ktos z przykladem nadludzia ?

**Comment by Cerdinski** [comment]
> Twa sila osiagnela nadludzki poziom.
> Twa zrecznosc osiagnela nadludzki poziom.
> Twa wytrzymalosc osiagnela nadludzki poziom.

Znalazlem, zostawiam tutaj na pozniej

**Comment by Cerdinski** [comment]
Zrobione
