### ISSUE TITLE
Brak info o wytraceniu

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#60]
Krotkowlosy gladkolicy mezczyzna szybkim niczym mysl ruchem smuklego bladoczerwonego miecza wytraca ci dlugi zdobiony lewak z reki. Czujesz paralizujacy bol w wykreconych ciosem dloniach.

**Comment by Cerdinski** [comment]
Bledna kotwica w triggerze, poprawiono
