### ISSUE TITLE
Ktoś podąża/przybywa. ktoto

### ISSUE THREAD

**Issue by Nurgiel** [Cerdinski/ArkadiaC#62]
Często się zdarza, że jakaś grupa dwójkowa szybko przebiegnie przez lokacje na której stoisz, fajnie byłoby móc kliknąć te osoby i sprawdzić `-ktoto`.

Być może to wróg i lepiej nie tracić czasu na wpisywanie `-ktoto <short>`, fajnie byłoby mieć możliwość szybkiego sprawdzenia poprzez kliknięcie w short(link) czy Ci co są przebiegli są w bazie przedstawionych.

Opcjonalnie:
1) Jeśli ktoś odszedł: podąża(ją) to link wywołuje tylko komende -ktoto,
2) jeśli ktoś przybył i stoi na lokacji to link wywołuje komende bb_obczaj, czyli oprócz -ktoto obejrzy i porówna cechy bo wcześniejszym sprawdzeniu czy dalej ta postać jest na lokacji, jak nie to patrz 1)

Powinno tworzyć linki (klikalne shorty) tylko jeśli Ci co przebiegli to potencjalni gracze, nie powinno tworzyć linków dla np. gwardii.

**Comment by Cerdinski** [comment]
done
