### ISSUE TITLE
Dzwon na statki - brakujace

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#63]
Bryg z wolna doplywa do brzegu. Gdy lad jest juz dostatecznie blisko, kilku marynarzy sprawnie zeskakuje na ziemie i cumuje statek. Na koniec z pokladu zsuniety zostaje drewniany trap, pozwalajac na swobodne zejscie na brzeg.
Dumny wysoki mezczyzna krzyczy: Doplynelismy do przystani u stop twierdzy Bodrog! Mozna wysiadac!
Dumny wysoki mezczyzna schodzi z brygu na brzeg.

Bryg z wolna doplywa do brzegu. Gdy lad jest juz dostatecznie blisko, kilku marynarzy sprawnie zeskakuje na ziemie i cumuje statek. Na koniec z pokladu zsuniety zostaje drewniany trap, pozwalajac na swobodne zejscie na brzeg.
Dumny wysoki mezczyzna krzyczy: Doplynelismy do portu w Quenelles! Mozna wysiadac!
Dumny wysoki mezczyzna schodzi z brygu na brzeg.

**Comment by Cerdinski** [comment]
done
