### ISSUE TITLE
Niestandardowe opisy dobywania broni - zawod, gildia, klub

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#64]
Straznik
gzdobadz broni
Wiedziona naglym instynktem siegasz po srebrzysta kose bojowa.
Glad
gzdobadz broni
Jednym plynnym ruchem dobywasz wielkiej cwiekowanej maczugi.
Noz
gzdobadz sztyletow
Nieznacznym, wprawnym poruszeniem nadgarstkow wydobywasz z rekawow dwa masywne dlugie sztylety i dobywasz ich, a twoje oczy odruchowo zwezaja sie w waskie szparki.
Nieznacznym, wprawnym poruszeniem nadgarstka wydobywasz z rekawa dlugi zdobiony lewak i dobywasz go, a twoje oczy odruchowo zwezaja sie w waskie szparki.

**Comment by Cerdinski** [comment]
done
