### ISSUE TITLE
Ciag dalszy opisow niestandardowego dobywania broni

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#65]
Fanatyk
gzdobadz wszystkich broni
Pelnym pewnosci siebie ruchem dobywasz matowego starozytnego miecza i zdobionego jasniejacego mlota
bojowego, szykujac sie do zadawania swym przeciwnikom bolu i niesienia smierci.
Pelnym pewnosci siebie ruchem dobywasz polyskliwego smuklego espadona, szykujac sie do zadawania
swym przeciwnikom bolu i niesienia smierci.

opuszczenie broni gladiator
Bez pospiechu opuszczasz masywny zdobiony buzdygan.
XXX bez pospiechu opuszcza masywny zdobiony buzdygan. Mimo to z jej postawy wciaz bije gotowosc do
walki.

**Comment by Cerdinski** [comment]
done
