### ISSUE TITLE
Bind num0 bug siadanie

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#66]
usiadz przy za stolem
Gdzie chcesz usiasc? Za stolem, przy stole, za drugim stolem, przy drugim stole, za trzecim stolem, przy trzecim stole, za czwartym stolem, przy czwartym stole lub przy drewnianiej ladzie?
                                  BIND num0 [ USIADZ PRZY ZA STOLEM ]

**Comment by Cerdinski** [comment]
done
