### ISSUE TITLE
Atak - brak gaga przy lapaniu wszystkich przeciwnikow

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#67]
zabij ob_116389
zabij ob_159789
[ ATAKUJE ] wychudzona konajaca kobieta
                   A T A K U J E S Z ===>  zalamanego brudnego mezczyzne
                   A T A K U J E S Z ===>  piegowate obdarte dziecko
                   A T A K U J E S Z ===>  wychudzona konajaca kobiete

**Comment by Cerdinski** [comment]
done
