### ISSUE TITLE
Brak suba - cios speca

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#71]
Nie silac sie na wirtuozerie z calej sily walisz cienkonogiego czarnego pajaka na odlew dlugim runicznym korbaczem, obijajac mu przy tym tulow. Nieprzyjemne chrzakniecie i metny wzrok przeciwnika swiadcza, ze dobrze wymierzony cios musial trafic w jakies wrazliwe miejsce.

**Comment by Cerdinski** [comment]
U mnie to bardzo ladnie subuje

<----SB 1/6 cienkonogiego czarnego pajaka <- dlugim runicznym korbaczem 
 OGLUSZONO  cienkonogiego czarnego pajaka # dlugim runicznym korbaczem 

czy cos niezwyklego bylo przed albo po tym ?

**Comment by Cerdinski** [comment]
Wydaje sie dzialac poprawnie, jezeli sie potworzy, to nalezy zglosic ponownie wraz z instrukcja jak odtworzyc zeby blad sie pojawil
