### ISSUE TITLE
Proba zaslony czlonka druzyny przez 1 spacja - nie dziala

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#72]
Jak w temacie, mimo wyczyszczenia linii polecen nie bylam w stanie zaslonic poprzez "1 spacja"

**Comment by Cerdinski** [comment]
Pierwszy czlonek druzyny jest pod 2, pod jeden jestes ty, i to wysyla do muda 'wskaz siebie'
