### ISSUE TITLE
Suby magikow - runiczny korbacz - wip

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#73]
Z lekkiego zamachu dlugim runicznym korbaczem trafiasz groznego masywnego czarnego orka w nogi, pozostawiajac drobne obrazenia.
Celnym uderzeniem dlugiego runicznego korbacza trafiasz wielkiego muskularnego trolla w tulow, lekko go raniac.
Wykonujac ukosny zamach dlugim runicznym korbaczem trafiasz groznego masywnego czarnego orka w korpus, dotkliwie go raniac.
Wykorzystujac slabosc w obronie groznego masywnego czarnego orka, silnie uderzasz go w nogi dlugim runicznym korbaczem, ciezko raniac.
Widzac oslabienie twego przeciwnika, z poteznego zamachu dlugiego runicznego korbacza uderzasz poteznego masywnego trolla w tulow, pozostawiajac olbrzymie obrazenia.
Z poteznego zamachu dlugiego runicznego korbacza uderzasz barczystego zielonkawego goblina w glowe, masakrujac go i niemalze konczac te walke.

Wykonujesz silny zamach dlugim runicznym korbaczem, mierzac w olbrzymiego poteznego czarnego orka, lecz ten umiejetnie przyjmuje twa bron na wzmacniana drewniana tarcze.
Obszernym zamachem dlugiego runicznego korbacza usilujesz trafic olbrzymiego poteznego czarnego orka, jednak twoj przeciwnik zrecznym unikiem wymyka sie spoza zasiegu twej broni.

**Comment by Cerdinski** [comment]
Zabiore sie  za to, gdy opisy beda mniejwiecej kompletne

**Comment by Cerdinski** [comment]
Brakuje
BRZDEK
PUDLO
PAROWANIE

Reszta dodana

**Comment by Cerdinski** [comment]
Z braku nowych wpisow uznaje za zrobione. Jezeli ktos ma brakujace opisy, to prosze o zalozenie nowej issue
