### ISSUE TITLE
Brakujace w -room

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#77]
Rozroznienie -room gp na:
~~gp - miejsce gdzie mozna trenowac juz istniejace~~
~~med - miejsce gdzie mozna medytowac - #EFDB00~~
~~Usluga - #E2A253~~
~~Krawiec - #CCCAC9~~
Bronie/zbroje - #D87050
~~Zleceniodawcy - #DBC381
Bagna - #3B4227
Skup skor - #723A12
Ryby - #7EF7E5
Wozownia - #7A6945
Sady/pola uprawne - #6DC11F~~

**Comment by Cerdinski** [comment]
Jaka nazwa na bronie/zbroje ? Reszta dodana.

**Comment by Cerdinski** [comment]
done

**Comment by Cerdinski** [comment]
Bronie/zbroje - #D87050
To jednak nie zostal ododane
