### ISSUE TITLE
Podazanie na mapie

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#78]
Wraz z * pomagacie * przeniesc duza zelazna klatke na zachod.
Wraz z *, * i * wjezdzasz duzym drewnianym wozem na poklad *.

**Comment by Cerdinski** [comment]
Prosze... nie robcie za mnie patternow triggerow, dawajcie mi czysty, niezmieniony tekst :(
Choc w tym przypadku raczej nie bedzie to mialo znaczenia.

**Comment by Cerdinski** [comment]
done
