### ISSUE TITLE
Lokacje laczone -room

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#79]
Karczma + skup miesa + skup szczurow
Dylizans + woda + ryby?
Dylizans + list
Statek + woda? + ryby
Woda + ryby
Woda + ekspowisko
Woda + list

**Comment by Cerdinski** [comment]
Dodano mozliwosc dodatkowego typu lokacji,
Poszczegolne kombinacje rozwiazywane w skrypach glownego typu
