### ISSUE TITLE
Bindowanie lampy

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#81]
napelnij lampe olejem
zapal lampe
Butelka oleju jest pusta.
Probujesz zapalic migotliwa azurowa lampe, ale ci sie nie udaje... jest wyczerpana.

Fajnie by bylo jakby bind lapal ze butelka ktora probujemy napelnic jest pusta

**Comment by Inarrit** [comment]
Dobrze by bylo by po wpisaniu komendy 'zgas lampe' napelnianie lamy olejem znikalo z binda

**Comment by Cerdinski** [comment]
done
