### ISSUE TITLE
Bindowanie - kompas

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#84]
sprawdz polnoc
Widzisz jak szkielko porecznego kompasu peka, a cale urzadzenie po prostu rozpada ci sie w rekach.

Mogloby bindowac :
wez kompas z sakwy/torby/plecaka w zaleznosci od tego co postac ma wybrane za pojemnik
sprawdz polnoc

Short kompasu jest rozny, bo jest kilka typow.

**Comment by Cerdinski** [comment]
done, choc bez wyboru pojemnika (wymagaloby to jakiegos systemu ekwipunku, ktory nadal jest w fazie koncepcyjnej)
