### ISSUE TITLE
Ishtar - dylizanse WIP

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#85]
~~Sucha Kepa - Gelibol
Kupiecki stojacy woz z plandeka.~~

~~Maribor - Bodrog
Kolyszac sie przybywa otwarty jadacy powoz.
Otwarty jadacy powoz powoli zatrzymuje sie.
Otwarty stojacy powoz.~~

Novi - Oxen IDENTYCZNY POWOZ JAK MARI BODROG
Otwarty stojacy powoz. 

~~Maribor - Grabowa Buchta:
Toczac sie powoli przybywa drewniany jadacy woz.
Drewniany jadacy woz powoli zatrzymuje sie.
Drewniany stojacy woz.~~

~~Wyzima - Oxenfurt:
Kolyszac sie przybywa czarny jadacy dylizans.
Czarny jadacy dylizans powoli zatrzymuje sie.
Czarny stojacy dylizans. --> Zdublowany Ishtaryjski dylizans~~

~~Bialy Most - Rinde:
Kupiecki stojacy woz.~~

~~Woznica oznajmia gromkim glosem: Postoj, podgrodzie Tretogoru. 16167
Z zewnatrz dochodzi stlumiony glos woznicy: Postoj, srodek niewielkiej osady. 16137
Z zewnatrz dochodzi stlumiony glos woznicy: Postoj, glowny plac miasta. 16269~~

**Comment by Cerdinski** [comment]
Wykreslone rzeczy zostaly dodane. 
Brak czasu przejazdu i postojow, do dodania w przyszlosci jak beda, zeby wygladalo to tak samo jak w imperium
Novi-Oxen moge zaimplementowac dopiero, jak dostane lokalizacje GMCP w miejscach, gdzie sie zatrzymuje. Wpisz prosze 
#print %gmcp.room.info.map
na lokacjach gdzie sie zatrzymuje i wklej mi tutaj to, co wypisalo na ekranie

**Comment by Cerdinski** [comment]
done
