### ISSUE TITLE
Bindowanie -room - bledy

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#86]
https://pasteboard.co/Hy59uD9.png
Brak bindowania menu - zamiast tego wyjscie

**Comment by Cerdinski** [comment]
Nie moge tego odtworzyc. Czy dzieje sie to tylko po pierwszym ustawieniu lokacji na dany tym, czy po ponownym wejsciu na lokacje tez ?

**Comment by Cerdinski** [comment]
Ok, wystepuje tylko po pierwszym dodanie. Co tez wlasnie zostalo naprawione.
