### ISSUE TITLE
Brak suba - barb

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#91]
Nie tracac czasu na zbedne manewry z calej sily walisz szybkiego czarnego pajaka na odlew lsniacym poteznym morgensternem, gruchoczac mu przy tym tulow.

Nie przebierajac w srodkach z calej sily walisz nieduzego czarnego pajaka na odlew lsniacym poteznym morgensternem, gruchoczac mu przy tym tulow. Nieprzyjemne chrzakniecie i metny wzrok przeciwnika swiadcza, ze dobrze wymierzony cios musial trafic w jakies wrazliwe miejsce.

**Comment by Cerdinski** [comment]
U mnie subuje.
Jakies kroki jak to odtworzyc ? Czyli co zrobic zeby sie stalo ponownie ?

**Comment by Cerdinski** [comment]
powinno dzialac, bug z wylapytaniem kolorowania w niektorych przypadkach
