### ISSUE TITLE
Teleporty dylizansow Ishtar

### ISSUE THREAD

**Issue by Inarrit** [Cerdinski/ArkadiaC#92]
Woznica oznajmia gromkim glosem:
Z zewnatrz dochodzi stlumiony glos woznicy: Postoj - plac w centrum Bialego Mostu.  2991

Z zewnatrz dochodzi stlumiony glos woznicy: Postoj - rozdroza niedaleko Piany. 3025

Z zewnatrz dochodzi stlumiony glos woznicy: Postoj - wies na podgrodziu Oxenfurtu. 20

Z zewnatrz dochodzi stlumiony glos woznicy: Postoj - wies Anchor. 288

Z zewnatrz dochodzi stlumiony glos woznicy: Postoj - pod Wyzima. 1222

**Comment by Cerdinski** [comment]
Done
