### ISSUE TITLE
Bledne cofanie

### ISSUE THREAD

**Issue by ghost** [Cerdinski/ArkadiaC#98]
Z trudnoscia schodzisz w dol.
SILY [5|9]
Odpadasz od sciany i lecisz w dol, jednak dzieki niewielkiej wysokosci udaje ci sie zgrabnie wyladowac na ziemi.

Cofnie na mapie na powrot na gore, o ile w przypadku wchodzenia na gore jest ok to w przypadku schodzenia juz nie.

**Comment by Cerdinski** [comment]
done
